name: CI

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      build_target:
        description: '选择编译平台 (Select Target)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

defaults:
  run:
    shell: bash

env:
  PACKAGE: "clash"
  RUST_TOOLCHAIN: "nightly"

jobs:
  compile:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extra-args: -F "plus"
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            extra-args: -F "plus"
            rustflags: "-C linker=aarch64-linux-gnu-gcc"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            postfix: ".exe"
            extra-args: -F "plus"

    # 逻辑判断：如果是手动触发，则匹配选择的 target
    if: |
      github.event_name != 'workflow_dispatch' || 
      github.event.inputs.build_target == 'all' || 
      github.event.inputs.build_target == matrix.target

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Build
        working-directory: clash-rs
        run: |
          cargo build --release --target ${{ matrix.target }} ${{ matrix.extra-args }} --package clash-rs
        env:
          RUSTFLAGS: --cfg tokio_unstable ${{ matrix.rustflags }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: clash-rs/target/${{ matrix.target }}/release/clash-rs${{ matrix.postfix }}
